### ISSUE TITLE
Unchainable?

### ISSUE THREAD

**Issue by kylebradshaw** [rpheath/jquery-flickr#1]
This project is exactly what I need for a photographer's site I am working on, but in the documentation you say the methods are chainable but I was unable to build upon the object once the photos methods were called. Can you confirm?

**Comment by rpheath** [comment]
Hmm... I must be honest, I haven't used this for a while now, but the "chaining" comes from this line: http://github.com/rpheath/jquery-flickr/blob/master/jquery.flickr.js#L82 - the $.flickr.self just has a reference to $(this), so doing "return $.flickr.self.each() { ... }" should return the jQuery set of selected elements, and allow you to chain more jQuery methods.

I do know this was working at one point, but again, I have not used this for a while. That's around the area you'd need to look to fix it, though. Hope that helps!
